# PostgreSQL configuration for all environments.
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "twitter_api_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME") { "twitter_api_test" } %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_PRODUCTION_NAME") { "twitter_api_production" } %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_PRODUCTION_CACHE_NAME") { "twitter_api_production_cache" } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_PRODUCTION_QUEUE_NAME") { "twitter_api_production_queue" } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_PRODUCTION_CABLE_NAME") { "twitter_api_production_cable" } %>
    migrations_paths: db/cable_migrate
